version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: test
      MARIADB_DATABASE: company
      MARIADB_USER: test
      MARIADB_PASSWORD: test
    volumes:
      - ./app/DB/init/:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
  app:
    image: gnshjoo/wanted
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
